services:
  - type: web
    name: trabajoconect-api
    env: node
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: ""
    startCommand: node api/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: db
      mountPath: /app/db
      sizeGB: 1
