services:
  - type: web
    name: trabajoconect-api
    env: node
    plan: free
    autoDeploy: true
    region: oregon
    branch: develop
    healthCheckPath: /health
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: node api/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /tmp/trabajoconect.db
      - key: npm_config_build_from_source
        value: "true"
